name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: ['1.20', '1.18', '1.17', '>=1.20']
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go_version }}

    - name: Create Docker Volume
      run: docker volume create postgres-data

    - name: Build-DB
      run: docker compose build

    - name: Create-DB
      run: docker compose up -d

    - name: Wait for PostgreSQL
      run: |
        for i in {1..10}; do
          docker exec $(docker ps -qf "name=postgres") pg_isready -U root -h localhost -p 5432 && break
          echo "Waiting for PostgreSQL to be ready..."
          sleep 5
        done

    - name: Test
      run: go test -v main_test.go

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: go build -v main.go
